# ============================================================
#  Managed by sshauto — regenerated by features/nginx_relay.py
#  Do not edit by hand; changes will be overwritten on the next
#  `sshauto update` or dashboard port change.
# ============================================================

# ---- Plain HTTP relay --------------------------------------
# Listens on every HTTP_PORTS entry on all interfaces.
# The Python proxy will upgrade the connection to a raw TCP tunnel.
server {
@HTTP_LISTEN_BLOCK@
    server_name _;
    tcp_nodelay on;

    client_header_timeout 86400s;
    client_body_timeout 86400s;
    client_max_body_size 0;

    location / {
        proxy_pass http://127.0.0.1:@PROXY_PORT@;
        proxy_http_version 1.1;
        proxy_set_header Host $host;

        # low‑latency streaming (buffering off)
        proxy_buffering off;
        proxy_request_buffering off;
        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;
        proxy_connect_timeout 10s;
        tcp_nodelay on;
    }
}

@HTTPS_SERVER_BLOCK@
