"""
Dropbear configuration layer targeting port 110 on localhost.
"""
from __future__ import annotations

from core.config import DROPBEAR_BANNER_PATH, DROPBEAR_DEFAULTS_FILE, state
from core.logger import log
from core.shell import Shell
from features.base import BaseFeature


class DropbearServiceFeature(BaseFeature):
    name = "dropbear_service"
    description = "Configure Dropbear on 127.0.0.1:110 as the core tunnel backend"
    depends_on = ["packages"]

    def is_installed(self) -> bool:
        if not DROPBEAR_DEFAULTS_FILE.exists():
            return False
        text = DROPBEAR_DEFAULTS_FILE.read_text()
        return "NO_START=0" in text and "127.0.0.1:110" in text

    def install(self) -> None:
        data = state.ensure_defaults()
        
        # Enforce destination port 110 strictly
        port = 110
        data["dropbear_port"] = port
        state.save(data)

        DROPBEAR_BANNER_PATH.write_text("Authorized Tunnel Access Only.\n")

        config = (
            "# Auto-generated by SSHAuto engine.\n"
            "NO_START=0\n"
            f'DROPBEAR_PORT="{port}"\n'
            f'DROPBEAR_EXTRA_ARGS="-p 127.0.0.1:{port} -b {DROPBEAR_BANNER_PATH} -W 65536"\n'
            'DROPBEAR_BANNER="' + str(DROPBEAR_BANNER_PATH) + '"\n'
            "DROPBEAR_RECEIVE_WINDOW=65536\n"
        )
        DROPBEAR_DEFAULTS_FILE.write_text(config)
        log.info(f"Dropbear isolated backend configured on 127.0.0.1:{port}")

        Shell.run("systemctl enable dropbear", check=False)
        Shell.run("systemctl restart dropbear")
        log.success("Dropbear system service recycled and verified ready.")

    def remove(self) -> None:
        Shell.run("systemctl stop dropbear", check=False)
        Shell.run("systemctl disable dropbear", check=False)
