"""
Dropbear configuration layer targeting a specific port on localhost.
Uses a systemd drop‑in override to guarantee the command line, so
Dropbear never listens on port 22 by accident.
"""
from __future__ import annotations

from pathlib import Path

from core.config import DROPBEAR_BANNER_PATH, DROPBEAR_DEFAULTS_FILE, DROPBEAR_PORT_DEFAULT, state
from core.logger import log
from core.shell import Shell
from features.base import BaseFeature


class DropbearServiceFeature(BaseFeature):
    name = "dropbear_service"
    description = "Configure Dropbear on 127.0.0.1:<port> as the core tunnel backend"
    depends_on = ["packages"]

    def is_installed(self) -> bool:
        if not DROPBEAR_DEFAULTS_FILE.exists():
            return False
        text = DROPBEAR_DEFAULTS_FILE.read_text()
        return "NO_START=0" in text and "127.0.0.1:" in text

    def install(self) -> None:
        data = state.ensure_defaults()
        port = data.get("dropbear_port", DROPBEAR_PORT_DEFAULT)

        # 1. Write the legacy defaults file (still used by some init scripts)
        DROPBEAR_BANNER_PATH.write_text("Authorized Tunnel Access Only.\n")
        config = (
            "# Auto-generated by SSHAuto engine.\n"
            "NO_START=0\n"
            f'DROPBEAR_PORT="{port}"\n'
            f'DROPBEAR_EXTRA_ARGS="-p 127.0.0.1:{port} -b {DROPBEAR_BANNER_PATH} -W 65536"\n'
            'DROPBEAR_BANNER="' + str(DROPBEAR_BANNER_PATH) + '"\n'
            "DROPBEAR_RECEIVE_WINDOW=65536\n"
        )
        DROPBEAR_DEFAULTS_FILE.write_text(config)
        log.info(f"Dropbear defaults written (port {port})")

        # 2. Create a systemd drop‑in override to force the exact command
        service_name = self._detect_dropbear_service()
        if service_name:
            # Determine the binary path
            which = Shell.run("which dropbear", check=False)
            dropbear_bin = which.stdout.strip() if which.ok else "/usr/sbin/dropbear"

            # Build the override directory path
            # For a unit named "dropbear" or "dropbear.service", the drop‑in dir is "dropbear.service.d"
            unit_base = service_name if service_name.endswith(".service") else service_name + ".service"
            override_dir = Path("/etc/systemd/system") / f"{unit_base}.d"
            override_dir.mkdir(parents=True, exist_ok=True)

            # Remove any existing override files (clean slate)
            for f in override_dir.glob("*.conf"):
                f.unlink()
                log.debug(f"removed old override: {f}")

            # Write the new override
            override_file = override_dir / "force-port.conf"
            override_content = f"""[Service]
ExecStart=
ExecStart={dropbear_bin} -EF -p 127.0.0.1:{port} -W 65536 -b {DROPBEAR_BANNER_PATH}
"""
            override_file.write_text(override_content)
            log.info(f"systemd drop‑in override written: {override_file}")

            # Reload systemd and restart
            Shell.run("systemctl daemon-reload")
            Shell.run(f"systemctl enable {service_name}", check=False)
            Shell.run(f"systemctl restart {service_name}")
            log.success(f"Dropbear service ({service_name}) restarted with forced port {port}")
        else:
            log.warning("Could not detect systemd service; relying on /etc/default/dropbear and manual start.")
            # Fallback: try to start dropbear directly if it's not managed by systemd
            Shell.run("pkill dropbear", check=False)
            Shell.run(f"dropbear -p 127.0.0.1:{port} -W 65536 -b {DROPBEAR_BANNER_PATH} -E", check=False)

        # 3. Verify that Dropbear is actually listening on the correct port
        self._verify_binding(port)

    def remove(self) -> None:
        service_name = self._detect_dropbear_service()
        if service_name:
            Shell.run(f"systemctl stop {service_name}", check=False)
            Shell.run(f"systemctl disable {service_name}", check=False)
            # Remove the drop‑in override
            unit_base = service_name if service_name.endswith(".service") else service_name + ".service"
            override_dir = Path("/etc/systemd/system") / f"{unit_base}.d"
            if override_dir.exists():
                for f in override_dir.glob("*.conf"):
                    f.unlink()
                try:
                    override_dir.rmdir()
                except OSError:
                    pass
            Shell.run("systemctl daemon-reload", check=False)
        else:
            Shell.run("pkill dropbear", check=False)
        log.info("Dropbear removed")

    def _detect_dropbear_service(self) -> str | None:
        """Return the systemd service name (e.g., 'dropbear' or 'dropbear.service')."""
        for candidate in ("dropbear", "dropbear.service"):
            if Shell.run(f"systemctl status {candidate}", check=False).ok:
                return candidate
        return None

    def _verify_binding(self, expected_port: int) -> None:
        """Check that dropbear is listening on the loopback interface with the expected port."""
        result = Shell.run(f"ss -lpn | grep -E '127.0.0.1:{expected_port}.*dropbear'", check=False)
        if result.ok:
            log.success(f"Dropbear confirmed listening on 127.0.0.1:{expected_port}")
        else:
            log.warning(f"Could not verify Dropbear binding on 127.0.0.1:{expected_port}; "
                        "check with 'ss -lpn | grep dropbear'")
