"""
Network optimization plugin – BBR is optional via dashboard toggle.
"""
from __future__ import annotations

from pathlib import Path
from core.shell import Shell
from core.logger import log
from core.config import state
from features.base import BaseFeature

SYSCTL_CONF_PATH = Path("/etc/sysctl.d/99-sshauto-optimizer.conf")


class NetworkOptimizerFeature(BaseFeature):
    name = "network_optimizer"
    description = "Apply network tweaks (BBR optional)"
    depends_on = ["packages"]

    def is_installed(self) -> bool:
        return SYSCTL_CONF_PATH.exists()

    def install(self) -> None:
        data = state.ensure_defaults()
        enable_bbr = data.get("enable_bbr", True)

        log.info(f"Applying network tweaks (BBR: {'ON' if enable_bbr else 'OFF'})...")

        tweaks = [
            "# Auto-generated by SSHAuto",
            "net.ipv4.tcp_fastopen=3",
            "net.ipv4.tcp_low_latency=1",
            "net.ipv4.tcp_autocorking=0",
            "net.ipv4.tcp_notsent_lowat=16384",
            "net.ipv4.tcp_fin_timeout=15",
            "net.ipv4.ip_local_port_range=1024 65535",
            "net.ipv4.tcp_tw_reuse=1",
            "net.core.somaxconn=4096",
            "net.ipv4.tcp_max_syn_backlog=4096",
            "net.core.rmem_max=33554432",
            "net.core.wmem_max=33554432",
            "net.ipv4.tcp_rmem=4096 87380 33554432",
            "net.ipv4.tcp_wmem=4096 65536 33554432",
        ]

        if enable_bbr:
            tweaks.insert(0, "net.core.default_qdisc=fq")
            tweaks.insert(1, "net.ipv4.tcp_congestion_control=bbr")
        else:
            # Explicitly set CUBIC to ensure it's not BBR
            tweaks.append("net.ipv4.tcp_congestion_control=cubic")
            tweaks.append("net.core.default_qdisc=pfifo_fast")

        SYSCTL_CONF_PATH.parent.mkdir(parents=True, exist_ok=True)
        SYSCTL_CONF_PATH.write_text("\n".join(tweaks) + "\n")
        reload_res = Shell.run("sysctl --system", check=False)
        if not reload_res.ok:
            log.warning("Some sysctl parameters could not be reloaded instantly.")
        log.success(f"Network tweaks applied (BBR: {'enabled' if enable_bbr else 'disabled'}).")

    def remove(self) -> None:
        if SYSCTL_CONF_PATH.exists():
            SYSCTL_CONF_PATH.unlink()
        Shell.run("sysctl --system", check=False)
        log.success("Network tweaks removed.")
