from __future__ import annotations

from pathlib import Path
from core.logger import log
from core.shell import Shell
from features.base import BaseFeature
import time

SQUID_CONF = Path("/etc/squid/squid.conf")


class SquidProxyFeature(BaseFeature):
    name = "squid_proxy"
    description = "Install Squid proxy (listens on 127.0.0.1:3128)"
    depends_on = ["packages", "firewall", "nginx_relay"]  # ensure nginx config is ready

    def is_installed(self) -> bool:
        return SQUID_CONF.exists() and Shell.run("systemctl is-active squid", check=False).ok

    def install(self) -> None:
        log.info("Installing Squid proxy...")

        Shell.run("apt-get install -y squid", check=True)

        if SQUID_CONF.exists():
            SQUID_CONF.rename(SQUID_CONF.with_suffix(".conf.bak"))

        config = """
# Squid config generated by sshauto
http_port 127.0.0.1:3128
http_access allow all
cache deny all
forwarded_for delete
request_header_access X-Forwarded-For deny all
"""
        SQUID_CONF.write_text(config)
        log.info("Squid configured: listening on 127.0.0.1:3128.")

        # Test configuration
        test_result = Shell.run("squid -k parse", check=False, timeout=10)
        if not test_result.ok:
            log.error(f"Squid config test failed: {test_result.stderr}")
            raise Exception("Squid configuration is invalid.")

        # Reset failed state and start
        Shell.run("systemctl reset-failed squid", check=False)
        Shell.run("systemctl enable squid", check=False)

        # Start with longer timeout
        start_result = Shell.run("systemctl start squid", check=False, timeout=30)
        if not start_result.ok:
            log.warning(f"Squid start failed (exit {start_result.returncode}): {start_result.stderr}")
            log.info("Attempting to restart with fallback...")
            # Try restart with even longer timeout
            Shell.run("systemctl restart squid", check=False, timeout=30)

        # Final verification
        time.sleep(2)
        if Shell.run("systemctl is-active squid", check=False).ok:
            log.success("Squid proxy installed and running.")
        else:
            log.warning("Squid service is not active. Check logs with 'journalctl -u squid'.")

        log.important("Now all public HTTP ports (80, 8080, 8880, etc.) accept both WebSocket and plain HTTP.")

    def remove(self) -> None:
        Shell.run("systemctl stop squid", check=False)
        Shell.run("systemctl disable squid", check=False)
        SQUID_CONF.unlink(missing_ok=True)
        log.info("Squid removed.")
