from __future__ import annotations

from pathlib import Path
from core.logger import log
from core.shell import Shell
from features.base import BaseFeature

SQUID_CONF = Path("/etc/squid/squid.conf")


class SquidProxyFeature(BaseFeature):
    name = "squid_proxy"
    description = "Install Squid proxy (listens on 127.0.0.1:3128)"
    depends_on = ["packages", "firewall"]

    def is_installed(self) -> bool:
        return SQUID_CONF.exists() and Shell.run("systemctl is-active squid", check=False).ok

    def install(self) -> None:
        log.info("Installing Squid proxy...")

        Shell.run("apt-get install -y squid", check=True)

        if SQUID_CONF.exists():
            SQUID_CONF.rename(SQUID_CONF.with_suffix(".conf.bak"))

        config = """
# Squid config generated by sshauto
http_port 127.0.0.1:3128
http_access allow all
cache deny all
forwarded_for delete
request_header_access X-Forwarded-For deny all
"""
        SQUID_CONF.write_text(config)
        log.info("Squid configured: listening on 127.0.0.1:3128.")

        Shell.run("systemctl enable squid", check=False)
        Shell.run("systemctl restart squid", check=True)

        log.success("Squid proxy installed (loopback only). Nginx routes plain HTTP to it.")
        log.important("Now all public HTTP ports (80, 8080, 8880, etc.) accept both WebSocket and plain HTTP.")

    def remove(self) -> None:
        Shell.run("systemctl stop squid", check=False)
        Shell.run("systemctl disable squid", check=False)
        SQUID_CONF.unlink(missing_ok=True)
        log.info("Squid removed.")
