from __future__ import annotations

from pathlib import Path
from core.logger import log
from core.shell import Shell
from features.base import BaseFeature
import time

SQUID_CONF = Path("/etc/squid/squid.conf")


class SquidProxyFeature(BaseFeature):
    name = "squid_proxy"
    description = "Install Squid proxy – listens on 0.0.0.0:3128 (public)"
    depends_on = ["packages", "firewall"]

    def is_installed(self) -> bool:
        return SQUID_CONF.exists() and Shell.run("systemctl is-active squid", check=False).ok

    def install(self) -> None:
        log.info("Installing Squid proxy...")

        Shell.run("apt-get install -y squid", check=True)

        if SQUID_CONF.exists():
            SQUID_CONF.rename(SQUID_CONF.with_suffix(".conf.bak"))

        config = """
# Squid config generated by sshauto – public forward proxy on port 3128
http_port 0.0.0.0:3128

# Allow CONNECT to any port (1-65535)
acl SSL_ports port 1-65535
acl CONNECT method CONNECT
http_access allow CONNECT SSL_ports

# Allow all other requests
http_access allow all

# Performance tuning
cache deny all
forwarded_for delete
request_header_access X-Forwarded-For deny all
"""
        SQUID_CONF.write_text(config)
        log.info("Squid configured: listening on 0.0.0.0:3128 (public).")

        # Validate configuration
        test_result = Shell.run("squid -k parse", check=False, timeout=10)
        if not test_result.ok:
            log.error(f"Squid config test failed: {test_result.stderr}")
            raise Exception("Squid configuration is invalid.")

        # Reset failed state
        Shell.run("systemctl reset-failed squid", check=False)
        Shell.run("systemctl enable squid", check=False)

        # Restart with a generous timeout (handles both stop and start)
        restart_result = Shell.run("systemctl restart squid", check=False, timeout=90)
        if not restart_result.ok:
            log.warning(f"Squid restart returned exit {restart_result.returncode}. Trying start directly...")
            # Fallback: try start without restart
            Shell.run("systemctl start squid", check=False, timeout=60)

        time.sleep(2)

        # Final verification
        if Shell.run("systemctl is-active squid", check=False).ok:
            log.success("Squid proxy installed and running on port 3128.")
        else:
            log.warning("Squid service is not active. Check logs with 'journalctl -u squid'.")
            # Show last few lines
            Shell.run("journalctl -u squid --no-pager -n 10", check=False)

        log.important("Squid is now available as a forward proxy on port 3128.")
        log.important("Existing WebSocket relay on ports 80, 8080, 8880 remains unchanged.")

    def remove(self) -> None:
        Shell.run("systemctl stop squid", check=False, timeout=30)
        Shell.run("systemctl disable squid", check=False)
        SQUID_CONF.unlink(missing_ok=True)
        log.info("Squid removed.")
