"""
Installs sslh – a protocol demultiplexer for TLS/SSL.
"""
from __future__ import annotations

from pathlib import Path
from core.logger import log
from core.shell import Shell
from features.base import BaseFeature
import time

SSLH_CONF = Path("/etc/default/sslh")
SSLH_PORT = 443
NGINX_SSL_PORT = 8443
STUNNEL_PORT = 4443


class SslhDemuxFeature(BaseFeature):
    name = "sslh_demux"
    description = f"Install sslh: TLS demuxer on port {SSLH_PORT} (nginx on {NGINX_SSL_PORT}, stunnel on {STUNNEL_PORT})"
    depends_on = ["packages", "nginx_relay", "stunnel_tunnel"]

    def is_installed(self) -> bool:
        return SSLH_CONF.exists() and Shell.run("systemctl is-active sslh", check=False).ok

    def install(self) -> None:
        log.info(f"Installing sslh TLS demuxer on port {SSLH_PORT}...")

        Shell.run("apt-get install -y sslh", check=True)

        config = f"""
# sslh config – generated by sshauto
DAEMON="/usr/sbin/sslh"
DAEMON_OPTS="--user sslh --listen 0.0.0.0:{SSLH_PORT} --ssl 127.0.0.1:{NGINX_SSL_PORT} --ssh 127.0.0.1:{STUNNEL_PORT} --pidfile /var/run/sslh.pid"
"""
        SSLH_CONF.write_text(config)
        log.info(f"sslh configured: HTTPS → {NGINX_SSL_PORT}, raw SSL → {STUNNEL_PORT}.")

        Shell.run("systemctl reset-failed sslh", check=False)
        Shell.run("systemctl enable sslh", check=False)
        start_result = Shell.run("systemctl start sslh", check=False, timeout=30)
        if not start_result.ok:
            log.warning(f"sslh start failed (exit {start_result.returncode}). Trying restart.")
            Shell.run("systemctl restart sslh", check=False, timeout=30)

        time.sleep(2)
        if Shell.run("systemctl is-active sslh", check=False).ok:
            log.success(f"TLS demuxer active on port {SSLH_PORT}.")
        else:
            log.warning("sslh service is not active. Check logs with 'journalctl -u sslh'.")

        log.important("Nginx now listens on port 8443 for HTTPS (and any other HTTPS_PORTS except 443).")
        log.important("Clients can use port 443 for both HTTPS WebSocket and SSL tunnel (stunnel).")

    def remove(self) -> None:
        Shell.run("systemctl stop sslh", check=False)
        Shell.run("systemctl disable sslh", check=False)
        SSLH_CONF.unlink(missing_ok=True)
        log.info("sslh removed.")
