"""
Installs sslh – a protocol demultiplexer for TLS/SSL.
Uses a config file at /etc/sslh/sslh.conf for reliability.
"""
from __future__ import annotations

from pathlib import Path
from core.config import state
from core.logger import log
from core.shell import Shell
from features.base import BaseFeature
import time

SSLH_CONF_DIR = Path("/etc/sslh")
SSLH_CONF = SSLH_CONF_DIR / "sslh.conf"
SSLH_PORT = 443
NGINX_SSL_PORT = 8443
STUNNEL_PORT = 4443


class SslhDemuxFeature(BaseFeature):
    name = "sslh_demux"
    description = f"Install sslh: TLS demuxer on port {SSLH_PORT} (nginx on {NGINX_SSL_PORT}, stunnel on {STUNNEL_PORT})"
    depends_on = ["packages", "nginx_relay", "stunnel_tunnel"]

    def is_installed(self) -> bool:
        return SSLH_CONF.exists() and Shell.run("systemctl is-active sslh", check=False).ok

    def install(self) -> None:
        log.info(f"Installing sslh TLS demuxer on port {SSLH_PORT}...")

        Shell.run("apt-get install -y sslh", check=True)

        # Create config directory
        SSLH_CONF_DIR.mkdir(parents=True, exist_ok=True)

        # Write proper config file
        config = f"""
# sslh config generated by sshauto
verbose: false
foreground: false
inetd: false
numeric: false
transparent: false
timeout: 2
user: "sslh"

listen:
  - 0.0.0.0:{SSLH_PORT}

protocols:
  - name: "ssl"
    host: "127.0.0.1"
    port: {NGINX_SSL_PORT}
  - name: "ssh"
    host: "127.0.0.1"
    port: {STUNNEL_PORT}
"""
        SSLH_CONF.write_text(config)
        log.info(f"sslh config written to {SSLH_CONF}.")

        # Modify /etc/default/sslh to use the config file
        default_conf = Path("/etc/default/sslh")
        if default_conf.exists():
            # Backup original
            default_conf.rename(default_conf.with_suffix(".bak"))

        default_content = """
# sslh default config – managed by sshauto
DAEMON_OPTS="-F -f /etc/sslh/sslh.conf"
"""
        default_conf.write_text(default_content)
        log.info("Updated /etc/default/sslh to use config file.")

        # Force nginx to reload (it should have already been reconfigured)
        log.info("Reloading nginx to free port 443...")
        Shell.run("systemctl reload nginx", check=False, timeout=10)
        time.sleep(2)

        # Check if port 443 is free
        port_check = Shell.run("ss -lpn | grep ':443 '", check=False)
        if port_check.ok:
            log.warning("Port 443 is still occupied. Attempting to stop conflicting service.")
            pid_line = Shell.run("ss -lpn | grep ':443 ' | grep -oP 'pid=\\K[0-9]+'", check=False)
            if pid_line.ok and pid_line.stdout.strip():
                pid = pid_line.stdout.strip()
                log.info(f"Killing process {pid} on port 443.")
                Shell.run(f"kill -9 {pid}", check=False)
                time.sleep(2)

        # Start sslh
        Shell.run("systemctl reset-failed sslh", check=False)
        Shell.run("systemctl enable sslh", check=False)

        success = False
        for attempt in range(5):
            result = Shell.run("systemctl start sslh", check=False, timeout=10)
            if result.ok:
                success = True
                break
            log.info(f"sslh start attempt {attempt+1}/5 failed, retrying...")
            time.sleep(2)

        if success:
            log.success(f"TLS demuxer active on port {SSLH_PORT}.")
        else:
            log.warning("sslh service is not active after multiple attempts.")
            log.info("Check logs: journalctl -u sslh")
            # Check if port is now free
            port_check2 = Shell.run("ss -lpn | grep ':443 '", check=False)
            if port_check2.ok:
                log.error("Port 443 still occupied – please stop the service manually.")

        log.important("Nginx now listens on port 8443 for HTTPS (and any other HTTPS_PORTS except 443).")
        log.important("Clients can use port 443 for both HTTPS WebSocket and SSL tunnel (stunnel).")

    def remove(self) -> None:
        Shell.run("systemctl stop sslh", check=False)
        Shell.run("systemctl disable sslh", check=False)
        SSLH_CONF.unlink(missing_ok=True)
        Path("/etc/default/sslh").unlink(missing_ok=True)
        log.info("sslh removed.")
